spring:
  profiles:
    include: db
  #JPA
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          format_sql: true


#Log Level Config
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
